export default [
    {
        id: 1,
        img: "swimmer.png",
        rating: "5.0",
        reviewCount: 6,
        country: "USA",
        title: "Life lessons with Katie Zaferes",
        price: 136,
        openSpots: 0,
        location: "Online",
    },
    {
        id: 2,
        img: "swimmer.png",
        rating: "5.0",
        reviewCount: 6,
        country: "USA",
        title: "Life lessons with Katie Zaferes",
        price: 136,
        openSpots: 2,
        location: "Online",
    },
    {
        id: 3,
        img: "swimmer.png",
        rating: "5.0",
        reviewCount: 6,
        country: "USA",
        title: "Life lessons with Katie Zaferes",
        price: 136,
        openSpots: 3,
        location: "Online",
    },
]
